###
GET http://localhost:9000/api HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "isbn": "123456",
    "titulo": "Los 7 hábitos de las personas altamente efectivas",
    "autor": "Stephen Covey",
    "publicacion": "2023-04-17"
}